spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_leave?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #每次执行为更新数据库操作
    show-sql: true     #日志打印sql
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost
    port: 6379
    password: 123456
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
      timeout: 0
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: ch3-goods
#springboot对外暴露所有应用状态信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #开启普罗米修斯
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  #指标允许被导出
  metrics:
    export:
      prometheus:
        enabled: true